version: '3'

networks:
  laravel:

services:

  # NGINX Service

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - .:/var/www/html
      - .nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel

  # PHP Service
  php:
    build:
      context: .
      dockerfile: Dockerfile
      target: php
      args:
        - APP_ENV=${APP_ENV}
    container_name: php
    environment:
      - APP_ENV=${APP_ENV}
      - CONTAINER_ROLE=app  
    volumes:
      - .:/var/www/html
    ports:
      - 443:443
    depends_on:
      - mysql
    networks:
      - laravel

  # MYSQL Service
  mysql:
    image: mysql:8.0
    container_name: mysql
    volumes:
      - ./mysql:/var/lib/mysql
    restart: unless-stopped
    tty: true
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: clinic
      MYSQL_USER: clinic
      MYSQL_PASSWORD: cKLm7ruN2a49dskn
      MYSQL_ROOT_PASSWORD: u6Ha1mVq32d8AB7zK
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel
  
  # PhpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    volumes:
      - .:/var/www/html
    ports:
      - 9001:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - mysql
    networks:
      - laravel
  
  npm:
    image: node:12.18.0-alpine
    container_name: npm
    volumes:
      - .:/var/www/html
    ports:
      - 3000:3000
      - 3001:3001
      - 5173:5173
    working_dir: /var/www/html
    entrypoint: ['npm']
    networks:
      - laravel

volumes:
    data: ~