version: '3'

networks:
  laravel:

services:

  apache:
    image: httpd:2.4
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html
    networks:
      - laravel

  mysql:
    image: mysql:8.0.33
    container_name: mysql
    volumes:
      - ./mysql:/var/lib/mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: clinic
      MYSQL_USER: clinic
      MYSQL_PASSWORD: cKLm7ruN2a49dskn
      MYSQL_ROOT_PASSWORD: u6Ha1mVq32d8AB7zK
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel
  
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    volumes:
      - ./src:/var/www/html
    ports:
      - 9001:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - mysql
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laravel
  
  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ./src:/var/www/html
    working_dir: .
    depends_on:
      - php
    networks:
      - laravel
  
  npm:
    image: node:12.18.0
    container_name: npm
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']
    networks:
      - laravel

  artisan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: artisan
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
    working_dir: /var/www/html
    entrypoint: ['php', '/var/www/html/artisan']
    networks:
      - laravel