version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile2
    image: Laravel-clinic
    container_name: app
    restart: unless-stopped
    volumes:
      - ./ : /var/www
      - ./config/php/local.ini:/usr/local/etc/php/conf.d/local.ini
  webserver:
    build: 
      context: .
      dockerfile: Dockerfile_Nginx
    image: Laravel-clinic
    container_name: webserver
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./config/nginx/conf.d/:/etc/nginx/conf.d/