version: '3'

networks:
  laravel:

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - laravel

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: clinic
      MYSQL_USER: clinic
      MYSQL_PASSWORD: cKLm7ruN2a49dskn
      MYSQL_ROOT_PASSWORD: u6Ha1mVq32d8AB7zK
    tty: true
    ports:
      - 3306:3306  
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - laravel
volumes:
  db-data: ~